### ISSUE TITLE
Doesn't seem to respond to unmuting

### ISSUE THREAD

**Issue by EricAndrechek** [jpf/Zoom.spoon#2]
Love the project idea, but it doesn't seem to be working for me. When I open a new meeting it creates the red circle in my menu bar but doesn't allow me to mute by clicking it, nor does it update color when I unmute in Zoom. In watching the console I can see:
```
2020-11-03 21:26:52: updateZoomStatus(from-closed-to-running)
2020-11-03 21:26:52: -- Loading extension: uielement
2020-11-03 21:27:00: updateZoomStatus(muted)
2020-11-03 21:27:00: updateZoomStatus(from-running-to-meeting)
2020-11-03 21:27:26: updateZoomStatus(from-meeting-to-running)
2020-11-03 21:27:31: updateZoomStatus(from-running-to-closed)
```
But there is no muting or anything being registered. Let me know if there is anything else I can provide to help in debugging.

**Comment by jpf** [comment]
Argh! How frustrating. One thing to note is that, sadly, there isn't a good way for Hammerspoon to detect mute change events from Zoom without polling.

Thanks for your offer to help debug this. The console output above really helps.

Here's what I do when I'm developing the Zoom Spoon:

- Close Zoom
- Use the *Reload Config* menu item in Hammerspoon
- Open Zoom
- Start a Meeting

What _should_ happen is that you'll see a red or green circle in your menu bar, and if you click that circle, it should invert from red to green or green to red. The mute status in Zoom should also change.

As I'm trying to reproduce your error, I found that the Zoom Spoon isn't detecting Zoom closing, so I'm going to need to investigate that today too.

**Comment by tenitski** [comment]
Same problem - mute/unmute do not register. Tried with UI button and shortcuts.
There was a lot of muting, unmuting, start video, stop video and only the events registered were these:
```
2021-01-30 12:23:58: updateZoomStatus(unmuted)
2021-01-30 12:23:58: updateZoomStatus(from-running-to-meeting)
2021-01-30 12:24:41: updateZoomStatus(from-meeting-to-sharing)
2021-01-30 12:24:46: updateZoomStatus(from-sharing-to-meeting)
2021-01-30 12:24:56: updateZoomStatus(from-meeting-to-running)
```

**Comment by tenitski** [comment]
This is what I had to do in the end, a hybrid approach of using both Zoom events and global Zoom shortcut to toggle MUTE/UNMUTE. You must use the shortcut only though, no switching via UI.

The only problem is that Hammerspoon can only handle events if it was started before Zoom, otherwise it does not detect Zoom events. I had to restart Zoom a few times during testing, not sure how well it will work in a long run.

```
local inZoomMeeting = false
local isMuted = false

function micMuted()
    isMuted = true
    updateState(isMuted)
end

function micUmuted()
    isMuted = false
    updateState(isMuted)
end

function micToggled()
    isMuted = not isMuted
    updateState(isMuted)
end

function updateState(isMuted)
    if isMuted then
        hs.printf("Zoom has been MUTED")
        -- YOUR LOGIC HERE
    else
        hs.printf("Zoom has been UNMUTED")
        -- YOUR LOGIC HERE
    end
end

function meetingOff()
    -- YOUR LOGIC HERE
end

-- Listen to Zoom events
updateZoomStatus = function(event)
  hs.printf("updateZoomStatus(%s)", event)
  if (event == "from-running-to-meeting") then
    inZoomMeeting = true
  elseif (event == "muted") then
    micMuted()
elseif (event == "unmuted") then
    micUmuted()
elseif (event == "from-meeting-to-running") then
    inZoomMeeting = false
    meetingOff()
  end
end

hs.loadSpoon("Zoom")
spoon.Zoom:setStatusCallback(updateZoomStatus)
spoon.Zoom:start()

-- Listen to Zoom toggle mute shortcut
tap = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
    if inZoomMeeting then
        data = event:getRawEventData()
        flags = event:getFlags()
        -- CMD + SHIFT + A pressed - Zoom toggle mute shortcut
        -- 0 here is keyCode for A
        if data.NSEventData.keyCode == 0 and flags.cmd and flags.shift then
            micToggled()
        end
    end
    -- Dont kill the event, let Zoom handle it
	return false
end)
tap:start()
```

**Comment by brunon** [comment]
See this PR which adds the necessary polling logic to fix this issue: https://github.com/jpf/Zoom.spoon/pull/9

**Comment by johntdyer** [comment]
Do you have an example of #9 in use ?  Its not working for me and I am wondering if I am implementing it incorrectly based on the above example
